      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      # این مرحله به ما می‌گوید فایل‌های APK کجا ساخته شده‌اند
      - name: List APK files
        run: find . -name "*.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # این قسمت را فعلاً حذف کنید یا بگذارید باشد؛ با اجرای دستور بالا ما آدرس واقعی را پیدا می‌کنیم
          path: app/build/outputs/apk/debug/*.apk
