name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # قدم ۱: چک کردن اینکه آیا فایل gradlew واقعاً در ریشه هست یا نه
      - name: List files in root
        run: ls -la

      # قدم ۲: تلاش برای بیلد گرفتن (فقط با یک دستور ساده)
      - name: Build with Gradle
        run: ./gradlew assembleDebug
